//auth.js
export const USER_LOGGEDIN = 'USER_LOGGEDIN'
export const USER_LOGGEDOUT = 'USER_LOGGEDOUT'

//tool.js
export const RECEIVE_EXCHANGE_RATE = 'RECEIVE_EXCHANGE_RATE'


//article.js
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES'

//data.js
export const FETCH_AVAILABLE_CARDS_SUCCESS = 'FETCH_AVAILABLE_CARDS_SUCCESS'
export const FETCH_OWNED_CARDS_SUCCESS = 'FETCH_OWNED_CARDS_SUCCESS'
export const REGISTER_CARD_SUCCESS = 'REGISTER_CARD_SUCCESS'
